old_sound_rabbit_mq:
    connections:
        default:
            host:     'rabbitmq'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
    producers:
        events:
            connection:       default
            exchange_options: { name: 'events', type: direct }
            queue_options: {name: 'events', arguments: {'x-ha-policy': ['S', 'all']}}
    consumers:
        events:
            connection:       default
            exchange_options: {name: 'events', type: direct}
            queue_options: {name: 'events', arguments: {'x-ha-policy': ['S', 'all']}}
            callback: app.infrastructure.evens.elastic.store