sudo: true

dist: trusty

language: generic

env:
  - RELEASE=$TRAVIS_BUILD_NUMBER
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - stage: build docker envirorment
      script: bash ./resources/docker/build/scripts/build-push-docker-php-sf.sh
    - script: bash ./resources/docker/build/scripts/build-push-docker-nginx-web.sh
    - stage: testing (PHPUnit, PHPMD, PSR-2)
      script: docker run --rm $DOCKER_USERNAME/travis-ci-build:php-sf-$RELEASE ant phpunit
    - script: docker run --rm $DOCKER_USERNAME/travis-ci-build:php-sf-$RELEASE ant phpmd
    - script: docker run --rm $DOCKER_USERNAME/travis-ci-build:php-sf-$RELEASE ant psr2
    - script: docker run --rm $DOCKER_USERNAME/travis-ci-build:php-sf-$RELEASE ant behat
    - stage: functional testing (Behat)
      script:
      - cd resources/docker/test && bash building.sh $RELEASE
      - docker-compose exec php bin/behat