sudo: true

dist: trusty

language: generic

cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t $DOCKER_USERNAME/travis-ci-build resources/docker/php
      - docker images
      - docker push $DOCKER_USERNAME/travis-ci-build
    - stage: test
      script: docker run --rm -v $(pwd):/app $DOCKER_USERNAME/travis-ci-build ant phpunit
    - stage: test
      script: docker run --rm -v $(pwd):/app $DOCKER_USERNAME/travis-ci-build ant phpmd
    - stage: test
      script: docker run --rm -v $(pwd):/app $DOCKER_USERNAME/travis-ci-build  ant psr2