doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: '5.7'

        mapping_types:
            json: string

        types:
            siteIdentity: CmsBundle\Infrastructure\Model\Site\ValueObject\DoctrineSiteIdentityType
            userIdentity: CmsBundle\Infrastructure\Model\User\ValueObject\DoctrineUserIdentityType
            pageIdentity: CmsBundle\Infrastructure\Model\Page\ValueObject\DoctrinePageIdentityType

    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            dddCmdBundle:
                type: yml
                dir: "%kernel.root_dir%/../src/CmsBundle/Infrastructure/Persistence/Doctrine/Mapping"
                prefix: CmsBundle