NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v1/doc

cmsApiRest:
    resource: "@CmsApiRestBundle/Resources/config/routing.yml"
    prefix: /api/v1/