services:

    cms.application.site.create_site.create_site_command_handler:
        class: CmsBundle\Application\Site\CommandHandler\CreateSite\CreateSiteCommandHandler
        arguments:
            - '@cms.infrastructure.model.site.repository.doctrine_site_repository'

    cms.application.site.get_site.get_site_command_handler:
        class: CmsBundle\Application\Site\CommandHandler\GetSite\GetSiteCommandHandler
        arguments:
            - '@cms.infrastructure.model.site.repository.doctrine_site_repository'

    cms.application.user.create_user.create_user_command_handler:
        class: CmsBundle\Application\User\CommandHandler\CreateUser\CreateUserCommandHandler
        arguments:
            - '@cms.infrastructure.model.user.repository.doctrine_user_repository'

    cms.application.page.get_page.get_page_command_handler:
        class: CmsBundle\Application\Page\CommandHandler\GetPage\GetPageCommandHandler
        arguments:
            - '@cms.infrastructure.model.page.repository.doctrine_page_repository'

    cms.application.page.create_page.create_page_command_handler:
        class: CmsBundle\Application\Page\CommandHandler\CreatePage\CreatePageCommandHandler
        arguments:
            - '@cms.infrastructure.model.user.repository.doctrine_user_repository'
            - '@cms.infrastructure.model.site.repository.doctrine_site_repository'
            - '@cms.infrastructure.model.page.repository.doctrine_page_repository'

    cms.application.page.find_pages_by_user_id.find_pages_by_user_id_command_handler:
        class: CmsBundle\Application\Page\CommandHandler\FindPagesByUserId\FindPagesByUserIdCommandHandler
        arguments:
            - '@cms.infrastructure.model.page.repository.doctrine_page_repository'

    cms.application.page.find_pages_by_site_id.find_pages_by_site_id_command_handler:
        class: CmsBundle\Application\Page\CommandHandler\FindPagesBySiteId\FindPagesBySiteIdCommandHandler
        arguments:
            - '@cms.infrastructure.model.page.repository.doctrine_page_repository'