CmsBundle\Domain\Model\User\Entity\User:
    type: entity
    table: user
    repositoryClass: CmsBundle\Infrastructure\Model\User\Repository\DoctrineUserRepository
    id:
      id:
        type: userIdentity
        nullable: false
    fields:
      name:
        type: string
        nullable: false
      email:
        type: string
        nullable: true
      createdOn:
        type: datetime