CmsBundle\Domain\Model\Site\Entity\Site:
    type: entity
    table: site
    repositoryClass: CmsBundle\Infrastructure\Model\Site\Repository\DoctrineSiteRepository
    id:
      id:
        type: siteIdentity
        nullable: false
    fields:
      name:
        type: string
        nullable: false
      description:
        type: string
        nullable: true
      createdOn:
        type: datetime