CmsBundle\Cms\Domain\Model\Page\Entity\Page:
    type: entity
    table: page
    repositoryClass: CmsBundle\Cms\Infrastructure\Model\Page\Repository\DoctrinePageRepository
    id:
      id:
        type: pageIdentity
        nullable: false
    fields:
      content:
        type: string
        nullable: false
      status:
        type: integer
        nullable: true
      createdOn:
        type: datetime

    manyToOne:
      site:
        targetEntity: CmsBundle\Cms\Domain\Model\Site\Entity\Site
        joinColumn:
          name: site_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
        cascade:
          - all
      user:
        targetEntity: CmsBundle\Cms\Domain\Model\User\Entity\User
        joinColumn:
          name: user_id
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
        cascade:
          - all