page:
    type: rest
    resource: "@CmsApiRestBundle/Controller/Page/PageController.php"

user:
    type: rest
    resource: "@CmsApiRestBundle/Controller/User/UserController.php"

site:
    type: rest
    resource: "@CmsApiRestBundle/Controller/Site/SiteController.php"